import { Button } from "@/components/ui/button";
import Link from "next/link";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
<div>

<Navbar/>

<div className="flex items-center justify-center text-3xl text-black font-bold font-mono gap-3.5">
 <img className="h-40 w-40 rounded-4xl drop-shadow-2xl drop-shadow-blue-600 rounded-4xl" src="https://img.freepik.com/premium-photo/apple-computer_1166198-29258.jpg" alt="" />
 <h1>Apple mac</h1>
 <img className="h-40 w-40 rounded-4xl  drop-shadow-2xl drop-shadow-blue-600" src="https://item-shopping.c.yimg.jp/i/n/whatfun_pro-mkgq3-c_7_d_20230913140914" alt="" />
 <h1>Mac book</h1>
 <img className="h-40 w-40 rounded-4xl drop-shadow-2xl drop-shadow-blue-600" src="https://valkyrie.cdn.ifixit.com/media/2023/11/10080207/M3_Pro_t.jpg" alt="" />
 <h1>Apple</h1>
 <img className="h-40 w-40 rounded-4xl drop-shadow-2xl drop-shadow-blue-600" src="https://www.esm-computer.de/media/a9/f8/32/1689676003/apl-macbook-a1990-1_8cbc95b288acc935_autogenerated.webp" alt="" />
 <h1>Mac book</h1>
 </div>
 <div className="flex items-center justify-center text-2xl font-bold font-mono p-22 bg-gray-300 text-black">
  <h1>Asosiy modellari:

MacBook Air – yengil va ixcham, kundalik ishlar, o‘qish va ofis ishlari uchun ideal.

MacBook Pro – kuchliroq, dizaynerlar, dasturchilar va video montaj qiluvchilar uchun mos.

🔹 Afzalliklari:

🍏 macOS operatsion tizimi (xavfsiz va barqaror)

🔋 Uzoq batareya ishlash vaqti

⚡ Tez ishlaydigan Apple M-seriyali protsessorlar (M1, M2, M3 va boshqalar)

🎨 Sifatli Retina displey

🔒 Kuchli xavfsizlik tizimi

🔹 Kamchiliklari:

💰 Narxi qimmatroq

🎮 O‘yinlar uchun unchalik mos emas

🔌 Portlari kam (ayniqsa Air modelida)
🍏 1. Apple M-seriyali chiplar

Apple o‘z noutbuklarida endi Intel emas, balki M1, M2, M3 kabi maxsus ARM chiplaridan foydalanadi. Bu chiplar juda samarali:

⚡ Tez ishlash – ilovalar tez ochiladi, video tahrirlash va kod yozishda kuchli.

🔋 Kam quvvat sarfi – batareya uzoq vaqt ishlaydi.

🔇 Kam shovqin (fanlar tez o‘qmaydi).

💻 2. MacBook turlari va ularning farqlari
🟢 MacBook Air

🍃 Eng yengil va ixcham model

🏃‍♂️ Kundalik internet, ofis, film, hujjat bilan ishlashga juda qulay

🔋 Batareya uzoq – odatda 12–18 soatgacha

💼 Talabalar va ofis foydalanuvchilari uchun juda yaxshi

🔵 MacBook Pro

🚀 Kuchli protsessorlar, ko‘proq hotira va grafik imkoniyatlar

🎬 Video montaj, dizayn, dasturlash uchun a’lo

📺 Kattaroq displey variantlari (14″, 16″)

🔥 Fan bilan sovutish, murakkab vazifalarni yaxshi ko‘taradi

📺 3. Retina displey

MacBook’ning Retina displeyi juda aniq va ranglarni to‘g‘ri ko‘rsatadi:

📌 Yuqori piksellar – matn va rasm juda tiniq

🌈 Ranglar jonli va tabiiy ko‘rinadi

🔒 4. Xavfsizlik va maxfiylik

Apple quyidagilarni oson qiladi:

🔑 Touch ID – barmoq izi bilan tizimga kirish

🛡️ Ma’lumotlar shifrlanadi

📵 Virus va zararli dasturlarga qarshi kuchli himoya

🔄 5. Apple ekosistemi bilan uzviy aloqa

Agar sizda iPhone yoki iPad bo‘lsa:

📲 Fayllar AirDrop orqali tez yuboriladi

📞 iPhone qo‘ng‘irog‘ini Mac’da ko‘rish mumkin

📝 Bir formatda yozuv hamma joyda uchraydi

🧠 6. macOS operatsion tizimi

💡 Soddalik va qulay interfeys

🚀 Tezkor va barqaror ishlash

📦 App Store orqali ko‘plab ilovalar

🔄 Tizim yangilanishlari uzoq muddat beriladi

📉 7. Kamchiliklar (e’tiborga olish kerak)

💸 Narxi biroz yuqori

📦 Ba’zi Windows maxsus dasturlarni ishlatish qiyin bo‘lishi mumkin

🧰 Kuchli o‘yinlar uchun mos emas</h1>
 </div>
</div>

  );
}